config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'page#home'
  get "/contact" => "page#contact"
  get "/download" => "page#download"
  get "/faq" => "page#faq"
  get "/prototype" => "page#prototype"
  get "/prototype_info" => "page#prototype_info"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <meta charset="utf-8">
    <title>Easy Card</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
  <body>
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Easy Card</a>
        </div> <!-- /.navbar-header -->

        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="/download">Download</a></li>
            <% if user_signed_in? %>
              <li><%= link_to "Prototype", prototype_path %></li>
            <% end %>
            <li><a href="/faq">FAQ</a></li>
            <li><a href="/contact">Contact Us</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %> 

        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container -->
    </nav> <!-- /.navbar -->

    <% flash.each do |name, msg| %>
      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <img class="cat" src="http://iconbug.com/data/c7/512/cff6527915574c0cb3cd666b03d654a3.png">
        <%= msg %>
      </div>
    <% end %>

    <div id="top" class="jumbotron">
      <div class="container">
        <h1>Welcome to Easy Card</h1>
        <h2><i class="fa fa-quote-left fa-2x pull-left"></i><br> Easy Card fully digitizes business cards and allow you to carry around with you a mini library of contacts in your mobile devices wherever you go. <i class="fa fa-quote-right fa-2x pull-right"></i></h2><br>
        <p><a class="btn btn-warning btn-lg" href="/download">Download <span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
      </div> <!-- /.container -->
    </div> <!-- /.jumbotron -->

    <div class="container">
    <%= yield %>
    </div>

    <footer>
      <div class="container clearfix">
        <p class="pull-left">
          Copyright &copy; Easy Card 2014
        </p>
      </div> <!-- /.container -->
    </footer>

  </body>
</html>

app/views/page/contact.html.erb
<h3 id="benefits" class="subhead">Contact Us</h3>
<br><center>
<h3>Bates College<br>2 Andrews Rd<br>Lewiston, ME 04240<br>USA<br></h3>
<h4><span class="glyphicon glyphicon-earphone"> </span> 123-456-7890</h4></center><br><br>

<div class="container">
<form role="form" action="#" method="post" enctype="plain"> 
	<div class="form-group">
		<label for="name1">Name</label>
		<input type="name" name="Name" class="form-control" id="name1" placeholder="Your Name">
	</div>
	<div class="form-group">
		<label for="email1">Email address</label>
		<input type="email" name="Mail" class="form-control" id="email1" placeholder="Enter email">
		</div>
		<div class="form-group">
			<label>Enquiry or comments</label>
			<textarea class="form-control" name="Message" rows="3"></textarea>
		</div>
		<br>
		<button type="submit" class="btn btn-warning btn-lg" href="#">SUBMIT</button>
</form>
</div>

app/views/page/download.html.erb
<h3 id="benefits" class="subhead">Download Easy Card</h3>

<div class="row">
    <div class="col-md-4 col-sm-6 benefit">
    	<center><img class="img-responsive" src="http://www.att.com/wireless/iphone/assets/iphone-4s-devices.jpg"></center>
    	<h3>iPhone</h3>
    	<p><a href="#download">Download for iPhone</a></p>
    </div>
    <div class="col-md-4 col-sm-6 benefit">
    	<center><img class="img-responsive" src="http://www.att.com/shopcms/media/att/2013/shop/wireless/promotions/Galaxy-Mega/img-Galaxy-Mega-1.jpg"></center>
    	<h3>Android</h3>
    	<p><a href="#download">Download for Android</a></p>
    </div>
</div>

app/views/page/faq.html.erb
<h3 id="benefits" class="subhead">Frequently Asked Questions</h3>

<div class="row">
    <div class="col-md-4 col-sm-6 benefit">
    	<div class="benefit-ball">
            <span class="glyphicon glyphicon-globe"></span>
        </div>
    	<h3>General</h3>
    	<p>Blah blah blah...</p>
    </div>
    <div class="col-md-4 col-sm-6 benefit">
    	<div class="benefit-ball">
            <span class="glyphicon glyphicon-phone"></span>
        </div>
    	<h3>iPhone</h3>
    	<p>Blah blah blah...</p>
    </div>
    <div class="col-md-4 col-sm-6 benefit">
    	<div class="benefit-ball">
            <span class="glyphicon glyphicon-phone"></span>
        </div>
    	<h3>Android</h3>
    	<p>Blah blah blah...</p>
    </div>
    <div class="col-md-4 col-sm-6 benefit">
    	<div class="benefit-ball">
            <i class="fa fa-4x fa-cog fa-spin"></i>
        </div>
    	<h3>Technical Issues</h3>
    	<p>Blah blah blah...</p>
    </div>
</div>

app/views/page/home.html.erb
<h3 id="benefits" class="subhead">Why Use This Product</h3>
      <div class="row">
        <div class="col-md-4 col-sm-6 benefit">
          <div class="benefit-ball">
            <span class="glyphicon glyphicon-phone"></span>
          </div>
          <h3>Cross-platform</h3>
          <p>Easy Card caters for both iOS and Android mobile devices.</p>
    </div> <!-- /.benefit -->

    <div class="col-md-4 col-sm-6 benefit">
      <div class="benefit-ball">
        <span class="glyphicon glyphicon-th-list"></span>
        </div>
        <h3>Organize</h3>
        <p>Keeps your business cards organized based on contact names, company, date added and groups.</p>
    </div> <!-- /.benefit -->

        <div class="col-md-4 col-sm-6 benefit">
          <div class="benefit-ball">
            <span class="glyphicon glyphicon-user"></span>
          </div>
          <h3>Personal</h3>
          <p>Allows users to personalize their own business cards; but does not allow modification of others' business cards.</p>
        </div> <!-- /.benefit -->

        <div class="col-md-4 col-sm-6 benefit">
          <div class="benefit-ball">
            <span class="glyphicon glyphicon-transfer"></span>
          </div>
          <h3>Easy Transfer</h3>
          <p>Enjoy quick and easy transfer of business cards through QR Code, "Bump" or Bluetooth.</p>
        </div> <!-- /.benefit -->
      </div> <!-- /.row -->

      <div class="sect-border"></div>

      <h3 id="tour" class="subhead">A Tour of the Application</h3>
      <div class="row">
        <div class="col-md-12">
          <div id="slideshow" class="carousel slide">
            <ol class="carousel-indicators">
              <li data-target="#slideshow" data-slide-to="0" class="active"></li>
              <li data-target="#slideshow" data-slide-to="1"></li>
              <li data-target="#slideshow" data-slide-to="2"></li>
              <li data-target="#slideshow" data-slide-to="3"></li>
            </ol>

            <div class="carousel-inner">
              <div class="item active">
                <img src="http://i.imgur.com/8vttzRt.jpg">
                <div class="carousel-caption">
                  Contact list page
                </div>
              </div>
              <div class="item">
                <img src="http://i.imgur.com/x7kAFmx.jpg">
                <div class="carousel-caption">
                  Business Card
                </div>
              </div>
              <div class="item">
                <img src="http://i.imgur.com/obumjwt.jpg">
                <div class="carousel-caption">
                  Adding Contact
                </div>
              </div>
              <div class="item">
                <img src="http://visithub.files.wordpress.com/2011/04/how-to-shake-hands.jpg">
                <div class="carousel-caption">
                  :)
                </div>
              </div>
            </div>

            <a class="left carousel-control" href="#slideshow" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#slideshow" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div> <!-- #slideshow -->
        </div> <!-- /.col-md-12 -->
      </div> <!-- /.row -->

      <% if !user_signed_in? %>
        <center><h3><%= link_to "Sign Up", new_user_registration_path %> to get a better sense of the application!</h3></center>
      <% else %>
        <center><h3><%= link_to "Click here", prototype_path %> to get a better sense of the application!</h3></center>
      <% end %>

      <div class="sect-border"></div>

      <h3 id="about" class="subhead">The Team</h3>
      <div class="row">
        <div class="col-md-3 col-md-offset-1 text-center">
          <p><img class="img img-circle" src="http://traceygjones.files.wordpress.com/2010/06/bunnies_do_scream_by_misteringo.jpg" height="120px" width="120px" alt=""></p>
          <h4>Tze</h4><br>

          <p>The person who often has insomnia and came up with this idea in the middle of the night.</p><br>
        </div> <!-- /.col-md-4 -->
        <div class="col-md-3 col-md-offset-1 text-center">
          <p><img class="img img-circle" src="http://www.faithlineprotestants.org/wp-content/uploads/2010/12/facebook-default-no-profile-pic.jpg" height="120px" width="120px" alt=""></p>
          <h4>Person 1</h4><br>

          <p>TBA</p><br>
        </div> <!-- /.col-md-4 -->
        <div class="col-md-3 col-md-offset-1 text-center">
          <p><img class="img img-circle" src="http://www.faithlineprotestants.org/wp-content/uploads/2010/12/facebook-default-no-profile-pic.jpg" height="120px" width="120px" alt=""></p>
          <h4>Person 2</h4><br>

          <p>TBA</p><br>
        </div> <!-- /.col-md-4 -->
      </div> <!-- /.row -->

app/views/page/prototype.html.erb
<h1>Contacts</h1>
**Click on the contacts<br><br>

<div class="table-responsive">
<table class="table table-hover">
	<thead>
		<tr>
			<th>Fav.</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Company</th>
			<th>Date Added</th>
		</tr>
	</thead>
	<tbody>
		<tr class="clickablerow" onclick="window.document.location='/prototype_info';">
			<td><span class="glyphicon glyphicon-star"></span></td>
			<td>Amanda</td>
			<td>Watson</td>
			<td>Bates College</td>
			<td>13 May 2014</td>
		</tr>
		<tr class="clickablerow" onclick="window.document.location='/prototype_info';">
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>Bryan</td>
			<td>Adams</td>
			<td>Google</td>
			<td>1 Sep 2013</td>
		</tr>
		<tr class="clickablerow" onclick="window.document.location='/prototype_info';">
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>Caroline</td>
			<td>Williams</td>
			<td>Facebook</td>
			<td>20 Apr 2014</td>
		</tr>
		<tr class="clickablerow" onclick="window.document.location='/prototype_info';">
			<td><span class="glyphicon glyphicon-star"></span></td>
			<td>John</td>
			<td>Smith</td>
			<td>Twitter</td>
			<td>5 Oct 2013</td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>.</td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
		<tr>
			<td><span class="glyphicon glyphicon-star-empty"></span></td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
			<td>. </td>
		</tr>
	</tbody>
</table>
</div>

app/views/page/prototype_info.html.erb
<h1>Contact Info</h1>
<br><br>
<div class="table-responsive">
	<table class="table">
		<tbody>
			<tr>
				<td rowspan="3"><img class="img-responsive" src="http://www.mitais.com/images/global/empty_profile.jpg" width="100px"></td>
				<th>Name</th>
				<td>Amanda Watson</td>
			</tr>
			<tr>
				<th>Phone</th>
				<td><a href="#">123-456-7890</a></td>
			</tr>
			<tr>
				<th>Email</th>
				<td><a href="mailto:awatson@bates.edu">awatson@bates.edu</a></td>
			</tr>
			<tr colspan="3">
				<td>
				<a class="btn btn-primary btn-lg" role="button" href="#"><span class="glyphicon glyphicon-star"></span></a> 
				<a class="btn btn-danger btn-lg" role="button" href="#"><span class="glyphicon glyphicon-pencil"></span></a>
				</td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>
</div>
<br>
<h2>Business Card</h2>
<br>
<center>
<div class="card">
		<h3>Bates College</h3><br>
		<h4>Amanda Watson</h4><br>
		<h5>Admissions Officer</h5><br>
		<a href="#">123-456-7890</a><br>
		<a href="mailto:awatson@bates.edu">awatson@bates.edu</a>
</div>
</center>
<br>
<h2>Notes</h2>
<p>Met her at a career fair.
</p><br>
<%= link_to "Back", prototype_path %>